# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 12:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_by', models.CharField(max_length=255)),
            ],
        ),
    ]
